import React from "react";

export const prompts = [
  "Write about going back to school after summer vacation. ",
  "Write a thank you note to a friend who gave you onion andj garlic-flavored chewing gum.",
  "Draw an imaginary constellation. Write a story such as ancient people might have told about it.",
  "Describe a real made-up dream or nightmare.",
  "Write about your favorite childhood toy.",
  "Write out the best or the worst day of your life.",
  "Finish this thought: if I could change one thing about myself (if you can't think of anything, you might want to consider telling how you got to be perfect!)",
  "If and when I raise children, I'll never",
  "I have never been more frightened than when...",
  "Persuade a friend to give up drugs.",
  "Five years from now, I will be...",
  "Write about a day you'd like to forget.",
  "Invent and describe a new food.",
  "Describe an event that changed your life forever, or make up and describe an event that would change your life forever.",
  "Describe someone who is a hero to you and explain why.",
  ,
  "Write about a time in your life when you struggled with a choice and made the right one.",
  "Imagine yourself in a different century and describe an average day in your life.",
  "Which character from a book would you most like to meet and why?",
  "Three goals I have set for myself are...",
  "What would you do if 300 mice had just gotten out of their cages in a pet shop where you worked?",
  "What would you do if you were locked inside your favorite department store overnight?",
  "What would you do if you woke up one morning to find yourself invisible?",
  "What would you do if you were able to communicate with animals?",
  "What would you do if you could travel into the future?",
  "What would you do if you could travel into the past?"
];
